### ISSUE TITLE
マルチが0点になります。

### ISSUE THREAD

**Issue by jucky154** [JG1VPP/real#1]
https://github.com/JG1VPP/real/blob/1b46bdcf342971e9cddaa640ee217349650fea13/rtc.go#L135
において、マルチを0とするように返しているので、内部での得点が0になります。
リアルタイムコンテストではサーバ側が点数を返す仕様なので、0点でも問題はないかもしれないです。
よって、以下のどちらかの対応が必要だと考えています
・dll側で自分の得点表示（自分のコールサインはQSOデータから取得できるので可能だと考えられます）
・dll側で正しいマルチを返す(cfgのコンテスト定義が無効化されているので、01などという意味のないコンテストナンバーも弾かれずに通ってしまいます。コンテスト定義を実装する意味ではこちらも重要だと考えられます)

![マルチ未対応](https://user-images.githubusercontent.com/58735989/116773777-a2e81d00-aa92-11eb-9e85-dfbfa6df999c.png)

**Comment by JG1VPP** [comment]
ナンバーからマルチを抽出する処理はDLL側に移譲されていて、zreviseという関数がDLL側にあると思いますが、それの中でQSO構造体のMul1などのメンバー変数をDLL側でいじることで、zLogにデータを返すという仕組みになっています。

別件ですが、zverifyやzupdateという関数はそれぞれQSO1件の得点,総得点の計算をzLogから移譲されていて、やはりこれらも適切に実装しなければなりません。

**Comment by jucky154** [comment]
![現状](https://user-images.githubusercontent.com/58735989/117276354-c697d280-ae99-11eb-8d2c-dd51b025fbf5.png)
関数に得点計算のものが含まれていましたが、正しく計算されていません。
そもそも、コンテストナンバーが受け付けないです。shift + enterで無理やりログをつけたので得点計算がされていない可能性もあります。

**Comment by JG1VPP** [comment]
そのZLOファイルを開き直すと正しく点数が計算されると思います。
これは、ZyLOのバグではなく、zLogのバグという認識です。

**Comment by jucky154** [comment]
QSOsが2, Pointsが2でScoreが4として計算されました。multiが0ではあります。

**Comment by JG1VPP** [comment]
zLogのスコア画面でmultiが0になる原因は、QSOにNewMulti1が設定されていないためです:
https://github.com/nextzlog/zlog/blob/a031900f94cc5420c4fb917fd00745035032b2e8/zlog/UBasicScore.pas#L188

ユーザ定義コンテストでNewMulti1を設定しているのは、UGeneralMulti2というモジュールです:
https://github.com/nextzlog/zlog/blob/a031900f94cc5420c4fb917fd00745035032b2e8/zlog/UBasicScore.pas#L188

なぜ、QSOにNewMulti1が設定されないかというと、DATファイルが提供されていないからです。

とはいえ、リアルタイムコンテストではDATファイルを用意するより、DLLに内蔵させた方が良いでしょう。
(golangなら1行embedディレクティブを書くだけで簡単にDATファイルを埋め込めます)

その場合、zverify関数の中でQSO.SetNewMul1を呼ぶことが重要です。
既に、最新のcommitにてそのように実装しました。

あとは、そのzverify関数の中で、マルチが有効かどうかを判定する処理を加えましょう。

**Comment by jucky154** [comment]
申し訳ありません。「embedディレクティブ」とはなんでしょうか？
https://zenn.dev/koya_iwamura/articles/53a4469271022e
を見てみたものの、どのようなものなのかがいまいちピンときていません

**Comment by JG1VPP** [comment]
zLog v2.6.0.10z3をリリースしました。
QSOの入力時にzupdate関数に渡されるQSOが、最新のQSOを含むようになりました。

**Comment by JG1VPP** [comment]
例えば、

`//go:embed real.dat`
`var city_real_dat []byte`

と書き込めば、配列`city_real_dat`にreal.datの内容がコンパイル時に格納されます。
これがembedです。

**Comment by JG1VPP** [comment]
例えば、

//go:embed real.dat
var city_real_dat string

と書き込めば、変数city_real_datにreal.datの内容がコンパイル時に格納されます。
これがembedです。

**Comment by jucky154** [comment]
https://github.com/JG1VPP/real/blob/master/real.go#L120
verify関数を修正しました。

https://github.com/JG1VPP/real/blob/master/real.go#L78
makemap関数で{シリアルナンバー,bandのbyteのstring}
とするようにしました。（つまり、シリアルナンバーとbandが一致しているところだけ1とする。デフォルトが0です）
zverify関数ではnewmulti関数は過去に更新した場合はfalseでないとダメだと考えた書き方にしています
のちにmapを+1することで2以上にしてmultiとしては有効だが、newではないという扱いにしています

動作確認としてはmultiの方は正常に動作しましたがPointsが0になってしまいました。

**Comment by jucky154** [comment]
この辺の関数の動作がいまいちわかっていないので確認のほどお願いします

**Comment by jucky154** [comment]
![multiは動いた](https://user-images.githubusercontent.com/58735989/117576088-73cf4c80-b11f-11eb-9916-634733c46076.png)

現状の写真です。
なぜか作れたバグデータですけど、QSO数*multi数としている関係でコールサインの入っていない無効なはずの交信が得点計算されています…。
https://github.com/JG1VPP/real/blob/master/real.go#L127
では空白を無効としているはずなのに…。（可能性としてあるのはスペースが入力されていてその関係で弾かれていないというだけかもしれません。

また、zlogのバグのせいでこのまま入力してもQSO数とmultiが増えてもscoreは増えません…。

**Comment by jucky154** [comment]
交信を一つ削除しても適切にマルチなどが削除されることも確認しました。よってマルチの判別については問題ないと考えられます。

![10が11に](https://user-images.githubusercontent.com/58735989/117576972-cc541900-b122-11eb-91cd-4b2564f144a8.png)
しかし、周波数を変えた場合は上のようになぜか10が11にされてしまいました…

**Comment by JG1VPP** [comment]
Pointsが0になる理由ですが、zLog側で反映させる処理を忘れてました。すみません、fixします。

**Comment by JG1VPP** [comment]
確認します。

**Comment by JG1VPP** [comment]
まず、コールサインなしのQSOですが、そもそもShift+Enterでも入力できないと思います。
zLog v2.6.0.10z4を使っていますか？
私の環境では弾かれて入力できませんでした。

**Comment by jucky154** [comment]
コールサインなしQSOはなぜか作れたバグです…（zLog v2.6.0.10z2あたりでたまたまできたデータを使っている感じです。debugに使えるかと考えて…）
コールサインなしQSOデータなんてあり得ないので、この空白による得点間違えについては気にしなくてもいい気はします

**Comment by JG1VPP** [comment]
zverify関数の中でscore=1を設定している処理、if文が実行されることはなさそうに見えますが、問題ないでしょうか？
if文の外でscore=3とすると、zLog側で1QSO3点になりました。

**Comment by jucky154** [comment]
if文の中身が実行されないということでしょうか？

https://github.com/JG1VPP/real/blob/master/real.go#L166
は実行されそうな気がするんですが…
一応はcallsignが空白でない　かつ　マルチのマップが0でない（マルチが存在する時）　とき実行されるので、良いと思っています。
（実際、newmultiの判定（10→11は除く）はうまくいっていますし…）

**Comment by JG1VPP** [comment]
実行されません。
その理由は以下のgolangのサンプルコードでわかります。
https://play.golang.org/p/-w5tVI0FTT_p

**Comment by jucky154** [comment]
https://github.com/JG1VPP/real/blob/master/real.go#L174
に修正し、
https://github.com/JG1VPP/real/blob/master/real.go#L179
まで到達していることはわかっている（Notifyでここのif文の中までは来ていることがわかっています）のですが、trueのところがうまくいかないのかpointは1になるものの、multiが0になります。

また、https://github.com/JG1VPP/real/blob/master/real.go#L170
のzverify関数は一度にすべてのログを流してくるのではなく、一個一個ログを流してくるということがわかったので、ここでmakemapするのは誤りでどこでmakemapすべきかと悩んでいます。

**Comment by JG1VPP** [comment]
得点計算の際に呼び出される関数の仕様は、再検討中です。
得点計算のたびに過去全てのQSOを参照することは非効率的です。
zLogでは、新規QSOだけを参照すれば得点計算できるように工夫されています。
ただし、zLog特有のスパゲティコードが原因で、zLogと同様の得点計算をDLLで行うのは難しいかもしれません。
しばらく時間をください。

あと、これはあまり本質的な問題ではありませんが、
1QSO毎にmakemapを呼び出すのはオーバーヘッドが大きく、
また、辞書のキーには文字列よりも整数値を使う方が効率的です。

**Comment by jucky154** [comment]
zverifyの動作がかなり厄介なことがわかりました
![2重チェック確認用コード](https://user-images.githubusercontent.com/58735989/118401723-b6ee6a00-b6a1-11eb-983f-86feac3c99b3.png)
で実行し
![試験データ](https://user-images.githubusercontent.com/58735989/118402234-ffa72280-b6a3-11eb-8705-7a3a5239367e.png)
をながすと
![2重チェックをしている](https://user-images.githubusercontent.com/58735989/118401730-c53c8600-b6a1-11eb-9062-f063f425aff0.png)
と交信データを二度流していることがわかりました。
また、最後に
![最後に空データを流してる](https://user-images.githubusercontent.com/58735989/118401812-1ba9c480-b6a2-11eb-93f2-0f904c2f89fb.png)
空の交信データを流してくることもわかりました。


さらに
![append点検用コード](https://user-images.githubusercontent.com/58735989/118401792-046ad700-b6a2-11eb-906b-f32ce31b8cd2.png)
で実行し
![appendデータ](https://user-images.githubusercontent.com/58735989/118402243-09c92100-b6a4-11eb-97f5-2fbe615776c6.png)
うえのデータに追加のデータをついかすると　
![appendではコールサインを2度流す](https://user-images.githubusercontent.com/58735989/118401805-12205c80-b6a2-11eb-9787-acc681e15964.png)
appendするだけでは全部の交信データは流してこず、入力したものだけを流してくることもわかりました。

しかし、問題点としては
![verify関数は勝手に動く](https://user-images.githubusercontent.com/58735989/118401856-48f67280-b6a2-11eb-95c5-fef00a057a51.png)
コールサインの入力をしてスペースキーを押してシリアルナンバーの欄に動いたり、交信を確定する前の状態でバンドを変更しただけでも勝手にverify関数は動いていることがわかりました。（上の画像はスペースキーを押したり、バンドをいじっただけで表示されました）


verify関数がかなり厄介な動き方をしているので手に負えない感じです。

**Comment by jucky154** [comment]
雰囲気としては確定前の情報は一度だけ流す。確定すると二度流すみたいな動きをしていました

**Comment by JG1VPP** [comment]
これは意図した動作であり、zverify関数の仕様です。
zverify関数はQSOの検査が必要であれば何度でも呼び出されます。

**Comment by jucky154** [comment]
となるとどうするのがいいのかと悩んでいます。
マルチかどうかを判断するには「これが交信確定かどうか（交信確定していなくてもverifyは動作するので）」「交信確定のときは二回とも同じものを吐き出す」という作業が必要になる気がしています。
その場合はどのようにすればいいでしょうか？

**Comment by JG1VPP** [comment]
まず、現状のzverify関数の仕様は忘れてください。

- DLL側のコードがスパゲティになりにくく、
- またzLog側に極力変更を加えず、
- かつ効率的な挙動となるように、

各関数の仕様を再検討しています。
概ね以下のように考えています。

1. ユーザがQSOを入力する
2. zverify関数が何度か呼び出され、QSOの得点やマルチが確定する
3. zLogにQSOが登録される
4. zinsert関数が呼び出される
5. zpoints関数が呼び出され、総得点が更新される

**Comment by JG1VPP** [comment]
zverify関数に渡されるQSOは、確定したQSOとは限りません。
例えば、zLog側でQSOを入力している最中にも呼び出されます。
具体的には、モードと周波数を変更した場合ですが、これは仕様です。

**Comment by jucky154** [comment]
そのような仕様であれば
1. 起動時にmakemap関数を呼ぶ
2. zverify関数ではmapのvalueからnewmultiかどうかを判定する
3. zinsert/zdelete関数でmapのvalueを更新する
とすれば自分のやり方でも問題ないように思いました。しかし、データのある.zloファイルを呼び出した時にはzverify関数しか動かないのでどうしたものかなという感じです

**Comment by JG1VPP** [comment]
zLog v2.6.0.10z5をリリースしました。
得点計算の問題が解消されています。
リアルタイムコンテストのDLLをこのバージョンに合わせて修正します。

**Comment by jucky154** [comment]
![得点計算](https://user-images.githubusercontent.com/58735989/119216594-7e221b00-bb0f-11eb-801e-e31c1a18c22d.png)
問題なく得点計算が行われました。もともと交信データがあった場合、交信データを追加した場合の両方で確認を行いました。

別件ですけど、気になった点としてはzattachがコンテスト選択直後に行われるのか、.zloの名前を決めたり、既存の.zloファイルを選ぶウィンドウと、realtimeコンテスト登録用のwindowが同時に出てきて、.zloファイルの名前を先に決めるとtoastでwebsocket繋がってないぞと永遠に言ってくるのが面倒だなという感じではありました。
