### ISSUE TITLE
new contestでフリーズする

### ISSUE THREAD

**Issue by jucky154** [JG1VPP/real#2]
new contestを選択するとフリーズをします
押さないように警告するか、原因を調査する必要があると考えています

**Comment by JG1VPP** [comment]
フリーズしている原因を切り分ける必要があります。
まず、
`git fetch`
`git checkout toast`
してください。
そして、DLLを作成してzLogで使ってください。
もし、この状態でも同じようにフリーズするのであれば、その原因はzLog側にあります。

**Comment by jucky154** [comment]
フリーズについては　https://github.com/JG1VPP/real/issues/3　と同様の問題でした。goroutineの停止の際に、停止したことを確認するところがうまく動かなかったのが原因でした。（goroutine停止確認がhttps://qiita.com/castaneai/items/7815f3563b256ae9b18d でいつの間にか消されていた）

しかし、new contestをするとzlogが全て消えるという初期からの問題は解決していません。new contestをする際にはログを保存していること、zlogを再立ち上げすれば同様のことが可能、ということから、注意喚起でも問題ないとは思います。

**Comment by JG1VPP** [comment]
FYI https://github.com/golang/go/issues/11100

**Comment by JG1VPP** [comment]
コンテスト終了時にFreeLibrary関数を呼び出してDLLを削除する部分に原因があります。
GolangにはGCを動かすためのスレッドが動いていますが、どうもこれが悪さをしているらしいです。
Golang側でこの問題に対する処置が公式にされていないので、メモリリークを承知でFreeLibraryをしない、という対応をするしかないのかもしれません。

**Comment by JG1VPP** [comment]
いっそのことGCのない言語、例えばRustで...

**Comment by JG1VPP** [comment]
このSetGCPercent関数でGCを無効化できるようですが、FreeLibrary直前にできるか、試してみます。
https://golang.org/pkg/runtime/debug/#SetGCPercent

**Comment by jucky154** [comment]
Rust使うのはいいと思います。
個人的にここまで勉強にかなりなったので。

いろいろやり直しで、私も院試・卒論・卒業設計も多いので時間大丈夫かなという感じはします…
（現状、sgとIBYさんに仕事を割振れていないのでその辺の意味でもやり直すのはアリな気がします。ただし、スケジュールをどうしていくかも含めて考える必要があると思います）

**Comment by JG1VPP** [comment]
お勧めはしません。Rustの学習はGoよりは遥かに難しく、最初のうちはコンパイルエラーを理解することさえできないかもしれません。

**Comment by JG1VPP** [comment]
別の考え方としては、そもそもDLLを閉じる必要があるのか、という点ですね。

現状では、DLLはリッチなCFGファイルのような位置付けです。
得点計算を始め、CFGファイルでは定義できない規約を表現します。
また、WebSocketや独自のGUIを表示する、といったことが実現できています。

でも、あくまでCFGファイルの代替なので、ALLJAや市郡では使えませんね。
JR2KHBさんの用途だと、ちょっと困りますね。

となると、コンテストをDLLで定義するというより、DLLはzLog全体の動作のカスタマイズに使う。
ALLJAや市郡の場合でも、zinsertなどの関数が動く。キーボードのイベントも拾える。

でも、得点計算だけは、ALLJAなど組み込みのコンテストでは行わない。

とまぁ、こんなところでしょうか。
得点計算アルゴリズムは、いくつかのコンテストにDLL側で対応する必要がありますが、
（もしくはコンテストごとにバージョンを作り、差し替え可能にする）

以上のような設計なら、そもそもNew Contest時にDLLを閉じる必要がない。
どうですか？

**Comment by jucky154** [comment]
私もそれが良いと思います。
もともと、zlogが得点計算をし、DLLがカスタマイズをするものだと考えていたので（issue#1の問題を急に書いたのはその辺を理解していなかったからです）

個人的には重いと批判がありましたが、ats4と同じコンテスト定義が得点計算アルゴリズムを負担し、 DLLがzlogをカスタマイズすればある程度は自由度が増すような気がします。
（実際、issue#1で得点計算の部分を対応しないといけないですし）

**Comment by JG1VPP** [comment]
得点計算は、Claimed scoreで良いのではないでしょうか？
規約に従って、とりあえず1点とする。
今後、ATS-4側で、リアルタイムにクロスチェックできなかったQSOを無効判定する、という可能性はあります。
その場合は、ATS-4から受け取ったデータに基づき、都度得点を修正すれば良いと思います。

DelphiにはGCがありませんので、zinsert関数で過去にアクセスしたことのあるQSOは、zdelete関数が呼ばれるまで、またはzLogでコンテストを閉じる瞬間まで、全く同じメモリアドレスに存在します。
つまり、DLL側でQSOをスライスにでも入れて参照を残しておき、ATS-4から採点結果を受け取った時に、QSOの得点をいじる、ということが可能です。

(GCがないと...のくだりは、GCの仕組みを調べてください。GCは、不要になったオブジェクトを消去し、そのうえ、メモリ上でデータを並べ替えてメモリアクセスを最適化します。従って、GCのある言語では、ポインタの指し示す実体は、常に書き換わります)

**Comment by JG1VPP** [comment]
ちなみに、重いというのは具体的に何が重いと感じるのでしょうか？
起動時にDLL側のウィンドウが表示されるまでフリーズする、というのはありますが、それは改善可能なはずです。

**Comment by jucky154** [comment]
https://qiita.com/gold-kou/items/4431d3dd41606d41732b
でGCについてはテキトーですが、お勉強中です。

重いというのは昔Twitterで上がっていた件です。（Lispによるコンテスト定義をしたzlogの時期の話です。https://twitter.com/nextzlog/status/1310953308786511881　)

得点計算はDLL側が負担する必要があるので、その例などをこちらで作る必要があり、現在、lispによるコンテスト定義がats4側に存在するので、それでLispやRubyでコンテストを定義できる新時代のzLogみたいにコンテストの規約に沿っているか評価してあげた方が主催者側がやりやすいのかなと思いました。
（ここまで書いて、どっちにしろ、DLLとlispは開発しないといけないので負担は変わらないかと思ってしまった）

**Comment by JG1VPP** [comment]
どうしてもlispが必要であれば、開発する必要はありません。
zbuildがDLLに埋め込むqxsl.exeこそ、ATS-4のコアであり、lispが内蔵されています。

というか既に、現状のZyLOでは、こっそりlispが動いていて、それは電子ログのマージ・エクスポート機能の形で活用されています。
なので、コンテストの定義をlispで書いておき、それをZyLOに処理させること自体は技術的に可能です。

細かいことを言うと、qxsl.exeはexeなので、DLLと違って直接オブジェクトをやり取りできません。
そこは、簡易的なサーバを立ててプロセス間通信を行う、などの裏技で対応はできます。

**Comment by jucky154** [comment]
そこまでlispを必要としているわけではありません。
開発の負担などを考えただけなので…

いずれにしろ
> コンテストをDLLで定義するというより、DLLはzLog全体の動作のカスタマイズに使う。
> ALLJAや市郡の場合でも、zinsertなどの関数が動く。キーボードのイベントも拾える。
> 
> でも、得点計算だけは、ALLJAなど組み込みのコンテストでは行わない。

という方針でいいと思います。

**Comment by JG1VPP** [comment]
最新のzLog v2.6.0.10z2で、このissueの内容を反映させました。
https://github.com/nextzlog/zlog/releases/tag/v2.6.0.10z2
最新のzbuildとともに使ってください。

**Comment by JG1VPP** [comment]
zLog v2.6.0.10z2では、DLLの名前は`zylo.dll`でなければなりません。
今まではCFGファイルと同じ名前でした。

**Comment by jucky154** [comment]
new contestをしてもクラッシュすることなく新しいコンテストに入ることができました
