### ISSUE TITLE
Use Dialog instead of Form

### ISSUE THREAD

**Issue by JG1VPP** [JG1VPP/real#4]
起動時に表示される、URLを入力するウィンドウですが、これはダイアログの方が良いと思います。
wincにNewDialogという関数があるので、NewFormの代わりに使ってみてはどうでしょうか？

なお、ダイアログにはSetModal(false)を設定してください。
ソースコードを見ればわかりますが、Modalがtrueになっていると、SEGVが発生します。
https://github.com/tadvi/winc/blob/5454f291903d0a962c0f6c54e6fb4dd633025041/dialog.go

**Comment by jucky154** [comment]
wincのexamplesにある機能しか見ていませんでした。
5/5の午後ごろに対応します。

**Comment by jucky154** [comment]
d8cc286736695555475d63311a4fd55b12b1ec27
で、dialogに変更しました。
![usedialog](https://user-images.githubusercontent.com/58735989/117094343-8acc1280-ad9e-11eb-9a10-cd21177152d5.png)

**Comment by JG1VPP** [comment]
ところで、ダイアログを表示する時、少しフリーズしませんか？

**Comment by jucky154** [comment]
ダイアログというよりも新しく2.6.1.0zを使い始めてからフリーズするような感じがありました（Formを使っても少しフリーズをしていました）

**Comment by JG1VPP** [comment]
今、zLog側でDLLを呼び出す際の手順を最適化していて、ZyLO由来のフリーズは軽減しました。
しかし、DLL側で重い処理を行うと、その間にzLogが待たされて、フリーズすることがあります。
例えば、ウィンドウやダイアログを作るという処理は重いので、フリーズの原因になると思います。

issueを立てておいてなんですが、単にURLを入力するダイアログを作るだけなら、DelphiのInputBoxを使うべきだなと思いました。
実際軽いです。
DLL側でInputBoxを使えるように、関数を作ります。

**Comment by JG1VPP** [comment]
zLog v2.6.0.10z2とともにリリースした最新のZyLOで`zylo.Prompt(label string, value string)(result string, ok bool)`という関数を追加しました。
labelはダイアログに表示される文字列、valueが文字列の初期値です。
ダイアログをOKボタンで閉じるとokにtrueが返ります。

**Comment by JG1VPP** [comment]
明日、この関数を使うように修正commitします。

**Comment by jucky154** [comment]
開始時に以下のようなtoastが出ました。
ダイアログが表示されるのと同時くらいでした。
![起動時](https://user-images.githubusercontent.com/58735989/117276701-20000180-ae9a-11eb-8968-6c036456f38d.png)

**Comment by JG1VPP** [comment]
コンテストを開いていないときにzinsert,zdelete関数が呼ばれないようにします。

**Comment by jucky154** [comment]
zlaunchはコンテスト起動時ではなく、zlog起動時に呼ばれるのでしょうか？　
https://github.com/JG1VPP/real/blob/master/real.go#L67

現在のコードだと起動時にmakewindow関数が呼び出されて、コンテスト選択中・.zloファイルの名前を決める際にもwindowが出てきています。

**Comment by JG1VPP** [comment]
zLog v2.6.0.10z3をリリースしました。
コンテストを開いていないときにzinsert,zdelete関数が呼ばれなくなりました。

**Comment by JG1VPP** [comment]
WebSocketに接続する際にウィンドウを表示するように改修しました。

**Comment by JG1VPP** [comment]
zylo.Prompt関数はgolangのdlgs(https://github.com/gen2brain/dlgs)と交代する形で削除しました。
なお、そもそもダイアログで入力させるのはUIとして不親切なので、
できればこちらのIssue(https://github.com/JG1VPP/real/issues/7)を検討してください。

**Comment by JG1VPP** [comment]
zylo.Prompt関数はgolangのdlgs (https://github.com/gen2brain/dlgs) と交代する形で削除しました。
なお、そもそもダイアログで入力させるのはUIとして不親切なので、
できればこちらのIssue (https://github.com/JG1VPP/real/issues/7) を検討しましょう。
