### ISSUE TITLE
If a contest is not selected, zlog throws an error

### ISSUE THREAD

**Issue by jucky154** [JG1VPP/real#6]
![何もせず終了](https://user-images.githubusercontent.com/58735989/117276879-4887fb80-ae9a-11eb-8e31-786d1c84f9a5.png)
コンテスト選択画面で、コンテストを選ばず終了するとpanicしました。
致命的なエラーには見えないので、問題ないとは思いますが、一応報告しておきます。

**Comment by JG1VPP** [comment]
これはreal.goの問題なので、zdetach関数でWebSocketの待機を解除している処理を修正してください。

**Comment by jucky154** [comment]
出なくなりました。対応ありがとうございます。
