### ISSUE TITLE
Get Server URL via Redirect

### ISSUE THREAD

**Issue by JG1VPP** [JG1VPP/real#7]
WebSocketの接続先URLは、現在は手動入力ですが、以下のような仕組みで自動化できます。

1. ユーザにzLogを起動してもらう
2. ユーザがリアルタイムコンテストのCFGファイルを選ぶ
3. DLL側で、`zattach("REAL-TIME CONTEST", "/path/to/real.cfg")`が呼び出される
4. DLL側で、localhost:12345にて待ち受け用サーバを起動させる
5. DLLがブラウザを起動して、登録ページを開く
6. 登録が完了したら、ATS-4からlocahost:12345にページ遷移する（この処理はATS-4に実装する）
7. ページ遷移の際にURLパラメータを受け取り、それをもとにWebSocketの接続先URLを取得する

**Comment by JG1VPP** [comment]
待ち受け用サーバは、goの標準ライブラリを使って、簡単に実装できます。
https://astaxie.gitbooks.io/build-web-application-with-golang/content/ja/03.2.html

**Comment by jucky154** [comment]
その方向で開発を進めます。まずは、zylo関係なしに、go 標準ライブラリの動作などを実験するので少々時間をください。
また、この方法で不安なのは「zlogを停止し、再度接続する際に再登録扱いで前回のログが削除される可能性があることです」
その辺のためにどこかにURLを保存しておきたいです。
前回の方法では、一応メモ帳に保存せよという雑な対策が存在することはできましたが、今回はそれができないので。

**Comment by JG1VPP** [comment]
一時的にデータを保管したいのであれば、レジストリを使うか、ファイルを保存すれば良いと思います。

**Comment by jucky154** [comment]
https://github.com/JG1VPP/real/blob/master/real.go#L147
についてはcfgファイルの最後のところなどに書いてもらって、cfgファイルを読み込んで、readしようかなと思っています。（汎用性を保つため）

https://github.com/JG1VPP/real/blob/master/real.go#L149
で並列処理にサーバ関連を実行してもらっています。（go funcでないとフリーズしました）
https://github.com/JG1VPP/real/blob/master/real.go#L126
https://github.com/JG1VPP/real/blob/master/real.go#L111
でサーバの関数があり、localhost:12345/?url_long=~にurlが来るとCONnect WebSocketされて、mainWindowが開くという形にしました。

また、これで一応は動いたんですけど
https://github.com/JG1VPP/real/blob/master/real.go#L112
の実行が、
https://github.com/JG1VPP/real/blob/master/real.go#L120
と同時のため、ブラウザへの"get url!"という表示がmakeWindowなどしながらなのでワンテンポ遅れ気味という感じです。

一応は
https://github.com/JG1VPP/real/blob/master/real.go#L147
でブラウザを開かせようとしたのですが、なぜかうまくいきませんでした。

**Comment by JG1VPP** [comment]
素晴らしいです。

ブラウザを起動するのは、ライブラリがあります。
https://golang.org/pkg/cmd/internal/browser/

見た感じWindowsでもmacでも動きます。

**Comment by jucky154** [comment]
https://golang.org/pkg/cmd/internal/browser/
はintetnalで外部から呼び出せなかったので、
https://pkg.go.dev/github.com/pkg/browser
を使ってみましたが、ダメでした。

どちらにしてもexe（exec.Command("rundll32.exe", "url.dll,FileProtocolHandler", conurl).Start()　、https://github.com/JG1VPP/real/blob/master/real.go#L147　
)で開いている感じなので、やっていることは同じかと思います。（普通にDLLではない実行方法ではすぐにブラウザが開いたのですが、DLLの場合は待てど暮らせど何も開かず1分くらい経っても何も起きないという感じです）

**Comment by jucky154** [comment]
申し訳ありません。URLの書き方が不適切だったのが原因だったようです。
https://
を追加した場合
exec.Command("rundll32.exe", "url.dll,FileProtocolHandler", conurl).Start()　
でchromeを開くことに成功しました

**Comment by JG1VPP** [comment]
良かったです。

では、dlgsは不要になったということで、dlgsのimportを削除します。
このライブラリ、gopherjsに依存していて、更にgopherjsが大量のライブラリに依存していて、重すぎます。

**Comment by jucky154** [comment]
real.goのdlgsの方はこちらで削除しました

雑ではありますが。
https://github.com/JG1VPP/real/blob/master/real.go#L134
でcfgを読み込み、cfgの最後の行に書かれた
https://github.com/JG1VPP/real/blob/master/real.cfg#L43
登録サイトのurl , websocketに接続するためのurlを読み込み、接続できるようにしました。

これで、realtimeコンテスト形式のコンテストの場合は同じDLLを使いながらも、cfgファイルの最後を書き換えるだけで簡単に接続先を変えることができるようになりました。

**Comment by JG1VPP** [comment]
`go mod tidy`を実行し、不要な依存パッケージを消去しました。
